// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.Data;

#nullable disable

namespace ToDo.Migrations
{
    [DbContext(typeof(AtividadesDbContext))]
    partial class AtividadesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDo.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaConcluida")
                        .HasColumnType("bit");

                    b.Property<int?>("ListaAtividadesId")
                        .HasColumnType("int")
                        .HasColumnName("ListaAtividades<Atividade>Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListaAtividadesId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("ToDo.Models.ListaAtividades<ToDo.Models.Atividade>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ListasAtividades");
                });

            modelBuilder.Entity("ToDo.Models.Atividade", b =>
                {
                    b.HasOne("ToDo.Models.ListaAtividades<ToDo.Models.Atividade>", null)
                        .WithMany("Atividades")
                        .HasForeignKey("ListaAtividadesId");
                });

            modelBuilder.Entity("ToDo.Models.ListaAtividades<ToDo.Models.Atividade>", b =>
                {
                    b.Navigation("Atividades");
                });
#pragma warning restore 612, 618
        }
    }
}
